// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa9IKGS06zZ1BIwrNeOCDJSyi-vgHnLRA',
    appId: '1:659165155389:web:be59d1fbdcf314fd62da54',
    messagingSenderId: '659165155389',
    projectId: 'student-attendance-ebd3f',
    authDomain: 'student-attendance-ebd3f.firebaseapp.com',
    databaseURL: 'https://student-attendance-ebd3f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'student-attendance-ebd3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT4Nsb_-0SnpB0JfuB5jed9oQG6jRPCRs',
    appId: '1:659165155389:android:793366b1511529d862da54',
    messagingSenderId: '659165155389',
    projectId: 'student-attendance-ebd3f',
    databaseURL: 'https://student-attendance-ebd3f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'student-attendance-ebd3f.appspot.com',
  );
}
